In [41]:
import pandas as pd
import datetime as dt
import glob
import numpy as np

In [2]:
filelist = glob.glob('*.csv')
filelist.remove('metadata.csv')
filelist

['expedition_everest.csv',
 'rock_n_rollercoaster.csv',
 'soarin.csv',
 'splash_mountain.csv']

In [3]:
filelist[0][:-4]

'expedition_everest'

In [4]:
# For all of the filenames:
foof = {}

for filename in filelist:
    foof[filename[:-4]] = pd.read_csv(filename)

In [5]:
foof["expedition_everest"].tail()

              date             datetime  SPOSTMIN  SACTMIN
228807  10/31/2018  2018-10-31 20:10:00    -999.0      NaN
228808  10/31/2018  2018-10-31 20:17:00    -999.0      NaN
228809  10/31/2018  2018-10-31 20:24:00    -999.0      NaN
228810  10/31/2018  2018-10-31 20:30:00    -999.0      NaN
228811  10/31/2018  2018-10-31 20:38:00    -999.0      NaN

In [6]:
goof = {}

for foo in foof:
    foof[foo]["date"] = pd.to_datetime(foof[foo]["date"], format="%m/%d/%Y")
    foof[foo] = foof[foo][foof[foo]["SPOSTMIN"] != -999.0]
    goof[foo] = foof[foo].groupby("date").mean().reset_index()

In [7]:
type(foof["splash_mountain"]["date"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [8]:
goof["splash_mountain"].tail()

           date   SPOSTMIN    SACTMIN
2197 2018-10-27  32.803738  12.000000
2198 2018-10-28  12.659574  15.500000
2199 2018-10-29  47.047619   3.000000
2200 2018-10-30  20.743802  10.142857
2201 2018-10-31  15.182482  13.000000

In [9]:
metadata = pd.read_csv("metadata.csv")
metadata["DATE"] = pd.to_datetime(metadata["DATE"], format="%m/%d/%Y")
print(type(metadata["DATE"][0]))
metadata.rename(columns={"DATE" : "date"}, inplace=True)

metadata.tail()

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

,date,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,HOLIDAYPX,HOLIDAYM,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
2395,2018-07-26,regular,5,206,29,7,2018,SUMMER BREAK,23,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2396,2018-07-27,regular,6,207,29,7,2018,SUMMER BREAK,24,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2397,2018-07-28,regular,7,208,29,7,2018,SUMMER BREAK,25,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2398,2018-07-29,regular,1,209,30,7,2018,SUMMER BREAK,26,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2399,2018-07-30,regular,2,210,30,7,2018,SUMMER BREAK,27,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light

In [10]:
maxdate = metadata["date"].max()
mindate = "01/01/2015"
print(maxdate)
mask = (metadata['date'] >= mindate) & (metadata['date'] <= maxdate)

2018-07-30 00:00:00

In [11]:
metadata = metadata.loc[mask]
metadata

,date,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,HOLIDAYPX,HOLIDAYM,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
1095,2015-01-01,NaN,5,0,0,1,2015,CHRISTMAS PEAK,0,5,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1096,2015-01-02,NaN,6,1,0,1,2015,CHRISTMAS,2,5,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1097,2015-01-03,NaN,7,2,0,1,2015,CHRISTMAS,3,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1098,2015-01-04,NaN,1,3,1,1,2015,CHRISTMAS,4,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1099,2015-01-05,NaN,2,4,1,1,2015,CHRISTMAS,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1100,2015-01-06,NaN,3,5,1,1,2015,CHRISTMAS,6,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1101,2015-01-07,NaN,4,6,1,1,2015,CHRISTMAS,7,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1102,2015-01-08,NaN,5,7,1,1,2015,CHRISTMAS,8,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1103,2015-01-09,NaN,6,8,1,1,2015,CHRISTMAS,9,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1104,2015-01-10,NaN,7,9,1,1,2015,WINTER,10,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1105,2015-01-11,NaN,1,10,2,1,2015,WINTER,9,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1106,2015-01-12,NaN,2,11,2,1,2015,WINTER,8,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1107,2015-01-13,NaN,3,12,2,1,2015,WINTER,7,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1108,2015-01-14,NaN,4,13,2,1,2015,WINTER,6,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1109,2015-01-15,NaN,5,14,2,1,2015,MARTIN LUTHER KING JUNIOR DAY,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1110,2015-01-16,NaN,6,15,2,1,2015,MARTIN LUTHER KING JUNIOR DAY,4,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1111,2015-01-17,NaN,7,16,2,1,2015,MARTIN LUTHER KING JUNIOR DAY,3,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1112,2015-01-18,NaN,1,17,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,2,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1113,2015-01-19,NaN,2,18,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,0,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1114,2015-01-20,NaN,3,19,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,2,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1115,2015-01-21,NaN,4,20,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,3,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1116,2015-01-22,NaN,5,21,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,4,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1117,2015-01-23,NaN,6,22,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1118,2015-01-24,NaN,7,23,3,1,2015,WINTER,6,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1119,2015-01-25,NaN,1,24,4,1,2015,WINTER,7,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1120,2015-01-26,NaN,2,25,4,1,2015,WINTER,7,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1121,2015-01-27,NaN,3,26,4,1,2015,WINTER,6,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1122,2015-01-28,NaN,4,27,4,1,2015,WINTER,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1123,2015-01-29,NaN,5,28,4,1,2015,WINTER,4,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1124,2015-01-30,NaN,6,29,4,1,2015,WINTER,3,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2370,2018-07-01,peak,1,181,26,7,2018,SUMMER BREAK,4,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2371,2018-07-02,peak,2,182,26,7,2018,JULY 4TH,3,4,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2372,2018-07-03,peak,3,183,26,7,2018,JULY 4TH,2,4,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2373,2018-07-04,peak,4,184,26,7,2018,JULY 4TH,0,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2374,2018-07-05,regular,5,185,26,7,2018,JULY 4TH,2,4,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2375,2018-07-06,regular,6,186,26,7,2018,JULY 4TH,3,4,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2376,2018-07-07,regular,7,187,26,7,2018,SUMMER BREAK,4,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2377,2018-07-08,regular,1,188,27,7,2018,SUMMER BREAK,5,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2378,2018-07-09,regular,2,189,27,7,2018,SUMMER BREAK,6,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2379,2018-07-10,regular,3,190,27,7,2018,SUMMER BREAK,7,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2380,2018-07-11,regular,4,191,27,7,2018,SUMMER BREAK,8,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2381,2018-07-12,regular,5,192,27,7,2018,SUMMER BREAK,9,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2382,2018-07-13,regular,6,193,27,7,2018,SUMMER BREAK,10,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2383,2018-07-14,regular,7,194,27,7,2018,SUMMER BREAK,11,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2384,2018-07-15,regular,1,195,28,7,2018,SUMMER BREAK,12,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2385,2018-07-16,regular,2,196,28,7,2018,SUMMER BREAK,13,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2386,2018-07-17,regular,3,197,28,7,2018,SUMMER BREAK,14,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2387,2018-07-18,regular,4,198,28,7,2018,SUMMER BREAK,15,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2388,2018-07-19,regular,5,199,28,7,2018,SUMMER BREAK,16,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2389,2018-07-20,regular,6,200,28,7,2018,SUMMER BREAK,17,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2390,2018-07-21,regular,7,201,28,7,2018,SUMMER BREAK,18,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2391,2018-07-22,regular,1,202,29,7,2018,SUMMER BREAK,19,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2392,2018-07-23,regular,2,203,29,7,2018,SUMMER BREAK,20,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2393,2018-07-24,regular,3,204,29,7,2018,SUMMER BREAK,21,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2394,2018-07-25,regular,4,205,29,7,2018,SUMMER BREAK,22,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2395,2018-07-26,regular,5,206,29,7,2018,SUMMER BREAK,23,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2396,2018-07-27,regular,6,207,29,7,2018,SUMMER BREAK,24,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2397,2018-07-28,regular,7,208,29,7,2018,SUMMER BREAK,25,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2398,2018-07-29,regular,1,209,30,7,2018,SUMMER BREAK,26,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2399,2018-07-30,regular,2,210,30,7,2018,SUMMER BREAK,27,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light

In [12]:
moof = {}
for goo in goof:
    mask = (goof[goo]['date'] >= mindate) & (goof[goo]['date'] <= maxdate)
    goof[goo] = goof[goo].loc[mask]
    print(goo)
    
    print(goof[goo].head())
    moof[goo] = pd.merge(goof[goo], metadata, on = "date")

expedition_everest
           date   SPOSTMIN    SACTMIN
1094 2015-01-01  40.268817  10.500000
1095 2015-01-02  34.198113   5.500000
1096 2015-01-03  29.793814  24.333333
1097 2015-01-04  23.850000  25.000000
1098 2015-01-05  26.956522   3.000000
rock_n_rollercoaster
           date   SPOSTMIN  SACTMIN
1095 2015-01-01  74.717742     41.2
1096 2015-01-02  80.080645     26.0
1097 2015-01-03  88.222222     30.0
1098 2015-01-04   5.000000      NaN
1099 2015-01-05  62.321429     21.0
soarin
           date   SPOSTMIN    SACTMIN
1095 2015-01-01  89.814815  61.000000
1096 2015-01-02  82.389706  24.333333
1097 2015-01-03  73.443396        NaN
1098 2015-01-04  58.069307        NaN
1099 2015-01-05  58.437500        NaN
splash_mountain
          date   SPOSTMIN    SACTMIN
941 2015-01-01  28.156028  11.500000
942 2015-01-02  44.014085   1.000000
943 2015-01-03  43.198529  37.333333
944 2015-01-04  30.992063  16.000000
945 2015-01-31   6.724138        NaN

In [13]:
print(filelist[1])
moof[filelist[1][:-4]].head()

rock_n_rollercoaster.csv

,date,SPOSTMIN,SACTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
0,2015-01-01,74.717742,41.2,NaN,5,0,0,1,2015,CHRISTMAS PEAK,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1,2015-01-02,80.080645,26.0,NaN,6,1,0,1,2015,CHRISTMAS,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
2,2015-01-03,88.222222,30.0,NaN,7,2,0,1,2015,CHRISTMAS,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
3,2015-01-04,5.000000,NaN,NaN,1,3,1,1,2015,CHRISTMAS,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
4,2015-01-05,62.321429,21.0,NaN,2,4,1,1,2015,CHRISTMAS,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN

In [14]:
moof[filelist[1][:-4]].tail()

,date,SPOSTMIN,SACTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
1284,2018-07-26,63.206897,NaN,regular,5,206,29,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
1285,2018-07-27,65.566667,5.6,regular,6,207,29,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
1286,2018-07-28,46.726619,7.0,regular,7,208,29,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
1287,2018-07-29,45.856164,1.0,regular,1,209,30,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
1288,2018-07-30,46.493056,NaN,regular,2,210,30,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light

In [16]:
delete = ['AKFIREN', 'AKPRDDAY', 'AKPRDDN', 'AKPRDDT1', 'AKPRDDT2', 'HSPRDDN', 'HSPRDDT1', 'HSFIREWKS', 'HSPRDDAY', 'HSPRDDN', 'inSession_SoCal']
for moo in moof:
    moof[moo] = moof[moo].drop(delete, axis=1)

In [17]:
print(len(list(moof[moo].columns)))

182

In [42]:

for moo in moof:
    moof[moo] = moof[moo][np.isfinite(moof[moo]['SACTMIN'])]

In [43]:
moof[moo]

,date,SPOSTMIN,SACTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,...,HSFIRET2,HSFIREN,HSSHWNGT,HSSHWNT1,HSSHWNT2,HSSHWNN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
0,2015-01-01,28.156028,11.500000,NaN,5,0,0,1,2015,CHRISTMAS PEAK,...,NaN,NaN,3,18:30,20:00,Fantasmic!,0,NaN,NaN,NaN
1,2015-01-02,44.014085,1.000000,NaN,6,1,0,1,2015,CHRISTMAS,...,NaN,NaN,3,18:30,20:00,Fantasmic!,0,NaN,NaN,NaN
2,2015-01-03,43.198529,37.333333,NaN,7,2,0,1,2015,CHRISTMAS,...,NaN,NaN,2,18:30,20:00,Fantasmic!,0,NaN,NaN,NaN
3,2015-01-04,30.992063,16.000000,NaN,1,3,1,1,2015,CHRISTMAS,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
5,2015-02-01,16.721311,11.400000,NaN,1,31,5,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
7,2015-02-03,14.233333,2.500000,NaN,3,33,5,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
8,2015-02-04,13.129032,5.000000,NaN,4,34,5,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
9,2015-02-05,5.680000,3.000000,NaN,5,35,5,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
10,2015-02-06,20.843023,14.000000,NaN,6,36,5,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
11,2015-02-07,18.341709,31.000000,NaN,7,37,5,2,2015,WINTER,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
12,2015-02-08,19.365079,14.500000,NaN,1,38,6,2,2015,WINTER,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
13,2015-02-09,9.594595,3.000000,NaN,2,39,6,2,2015,WINTER,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
15,2015-02-11,13.545455,14.500000,NaN,4,41,6,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
16,2015-02-12,21.949686,15.500000,NaN,5,42,6,2,2015,PRESIDENTS WEEK,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
17,2015-02-13,16.016043,3.500000,NaN,6,43,6,2,2015,PRESIDENTS WEEK,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
20,2015-02-16,34.338624,14.200000,NaN,2,46,7,2,2015,PRESIDENTS WEEK,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
22,2015-02-18,18.316327,14.000000,NaN,4,48,7,2,2015,PRESIDENTS WEEK,...,NaN,NaN,0,NaN,NaN,NaN,0,NaN,NaN,NaN
24,2015-02-20,9.587912,15.000000,NaN,6,50,7,2,2015,PRESIDENTS WEEK,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
25,2015-02-21,20.386598,18.500000,NaN,7,51,7,2,2015,PRESIDENTS WEEK,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
26,2015-02-22,28.502825,35.000000,NaN,1,52,8,2,2015,PRESIDENTS WEEK,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
27,2015-02-23,25.696970,39.000000,NaN,2,53,8,2,2015,WINTER,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
28,2015-02-24,17.329545,18.666667,NaN,3,54,8,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
29,2015-02-25,13.478261,12.666667,NaN,4,55,8,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
30,2015-02-26,10.671141,8.333333,NaN,5,56,8,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
31,2015-02-27,5.638298,1.000000,NaN,6,57,8,2,2015,WINTER,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
32,2015-02-28,7.670455,3.000000,NaN,7,58,8,2,2015,WINTER,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
33,2015-03-01,25.789474,19.250000,NaN,1,59,9,3,2015,SPRING,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
34,2015-03-02,27.542373,21.500000,NaN,2,60,9,3,2015,SPRING,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
35,2015-03-03,26.506410,17.000000,NaN,3,61,9,3,2015,SPRING,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
36,2015-03-04,16.554878,11.000000,NaN,4,62,9,3,2015,SPRING,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1129,2018-06-22,67.083333,48.000000,regular,6,172,24,6,2018,SPRING,...,NaN,Star Wars: A Galactic Spectacular,1,21:00,NaN,Fantasmic!,2,21:15,22:15,Rivers of Light
1130,2018-06-23,67.366071,13.500000,regular,7,173,24,6,2018,SPRING,...,NaN,Star Wars: A Galactic Spectacular,1,21:00,NaN,Fantasmic!,2,21:15,22:15,Rivers of Light
1131,2018-06-24,59.072581,22.250000,regular,1,174,25,6,2018,SPRING,...,NaN,Star Wars: A Galactic Spectacular,1,21:00,NaN,Fantasmic!,2,21:15,22:15,Rivers of Light
1132,2018-06-25,79.854015,15.000000,peak,2,175,25,6,2018,SPRING,...,NaN,Star Wars: A Galactic Spectacular,1,21:00,NaN,Fantasmic!,2,21:15,22:15,Rivers of Light
1133,2018-06-26,72.703704,58.000000,peak,3,176,25,6,2018,SPRING,...,NaN,Star Wars: A Galactic Spectacular,1,21:00,NaN,Fantasmic!,2,21:15,22:15,Rivers of Light
1134,2018-06-27,73.795620,46.000000,peak,4,177,25,6,2018,SPRING,...,NaN,Star Wars: A Galactic Spectacular,1,21:00,NaN,Fantasmic!,2,21:15,22:15,Rivers of Light
1136,2018-06-29,63.876404,18.000000,peak,6,179,25,6,2018,SPRING,...,NaN,Star Wars: A Galactic Spectacular,1,21:00,NaN,Fantasmic!,2,21:15,22:15,Rivers of Light
1137,2018-06-30,38.811475,10.500000,peak,7,180,25,6,2018,SPRING,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1138,2018-07-01,52.796610,9.000000,peak,1,181,26,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1140,2018-07-03,69.210526,3.000000,peak,3,183,26,7,2018,JULY 4TH,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1141,2018-07-04,70.887097,13.000000,peak,4,184,26,7,2018,JULY 4TH,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1142,2018-07-05,70.275591,48.000000,regular,5,185,26,7,2018,JULY 4TH,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1143,2018-07-06,56.296296,31.000000,regular,6,186,26,7,2018,JULY 4TH,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1144,2018-07-07,45.625000,11.750000,regular,7,187,26,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1145,2018-07-08,47.892157,33.500000,regular,1,188,27,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1146,2018-07-09,70.595238,46.000000,regular,2,189,27,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1147,2018-07-10,69.205607,29.500000,regular,3,190,27,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1149,2018-07-12,61.386555,36.000000,regular,5,192,27,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1150,2018-07-13,63.225806,29.000000,regular,6,193,27,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1151,2018-07-14,49.909910,10.000000,regular,7,194,27,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1152,2018-07-15,52.698413,35.600000,regular,1,195,28,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1154,2018-07-17,69.072581,23.000000,regular,3,197,28,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1156,2018-07-19,67.317073,30.666667,regular,5,199,28,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1158,2018-07-21,46.678832,38.000000,regular,7,201,28,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1160,2018-07-23,61.560284,8.000000,regular,2,203,29,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1161,2018-07-24,57.264957,2.000000,regular,3,204,29,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1162,2018-07-25,67.744361,43.666667,regular,4,205,29,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1164,2018-07-27,62.435897,9.000000,regular,6,207,29,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1165,2018-07-28,41.048387,48.333333,regular,7,208,29,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light
1167,2018-07-30,57.934783,37.666667,regular,2,210,30,7,2018,SUMMER BREAK,...,NaN,Star Wars: A Galactic Spectacular,2,21:00,22:30,Fantasmic!,2,21:15,22:15,Rivers of Light

In [45]:
doof = {}
for moo in moof:
    doof[moo] = moof[moo].drop(["SPOSTMIN"], axis = 1)
    print(moof)
    print(doof[moo].head())

{'expedition_everest':            date   SPOSTMIN    SACTMIN WDW_TICKET_SEASON  DAYOFWEEK  DAYOFYEAR  \
0    2015-01-01  40.268817  10.500000               NaN          5          0
1    2015-01-02  34.198113   5.500000               NaN          6          1
2    2015-01-03  29.793814  24.333333               NaN          7          2
3    2015-01-04  23.850000  25.000000               NaN          1          3
4    2015-01-05  26.956522   3.000000               NaN          2          4
5    2015-01-06  26.666667  10.333333               NaN          3          5
6    2015-01-07  33.283582   9.000000               NaN          4          6
7    2015-01-08  30.846154  35.000000               NaN          5          7
8    2015-01-09  22.631579   7.666667               NaN          6          8
9    2015-01-10  24.340278  27.500000               NaN          7          9
10   2015-01-11  16.127451   9.500000               NaN          1         10
11   2015-01-12  11.936937   0.000000               NaN          2         11
12   2015-01-13   8.137255   3.000000               NaN          3         12
14   2015-01-15  15.891089  11.500000               NaN          5         14
15   2015-01-16  22.809524  22.250000               NaN          6         15
16   2015-01-17  33.308271  20.000000               NaN          7         16
17   2015-01-18  45.843750  16.833333               NaN          1         17
18   2015-01-19  42.163462  16.000000               NaN          2         18
19   2015-01-20  20.280374  33.000000               NaN          3         19
20   2015-01-21  19.303279  14.000000               NaN          4         20
21   2015-01-22  19.714286  13.100000               NaN          5         21
22   2015-01-23  16.495327   8.833333               NaN          6         22
23   2015-01-24  26.111111  20.333333               NaN          7         23
24   2015-01-25  34.126984  33.500000               NaN          1         24
25   2015-01-26  26.168224   4.500000               NaN          2         25
26   2015-01-27  16.941748   8.800000               NaN          3         26
27   2015-01-28  21.666667  17.800000               NaN          4         27
28   2015-01-29  19.634146  15.727273               NaN          5         28
29   2015-01-30  32.142857  19.500000               NaN          6         29
30   2015-01-31  24.712230  27.750000               NaN          7         30
...         ...        ...        ...               ...        ...        ...
1263 2018-06-23  52.946429   7.333333           regular          7        173
1264 2018-06-24  40.930233   5.000000           regular          1        174
1265 2018-06-25  41.000000  15.000000              peak          2        175
1266 2018-06-26  40.312500  70.000000              peak          3        176
1267 2018-06-27  38.333333  12.333333              peak          4        177
1268 2018-06-28  37.948718  14.166667              peak          5        178
1269 2018-06-29  38.956522  10.000000              peak          6        179
1270 2018-06-30  39.400000  24.666667              peak          7        180
1271 2018-07-01  37.520000  12.500000              peak          1        181
1272 2018-07-02  46.822430  26.000000              peak          2        182
1274 2018-07-04  32.198276  34.000000              peak          4        184
1276 2018-07-06  37.425743  31.666667           regular          6        186
1277 2018-07-07  34.956897  14.250000           regular          7        187
1278 2018-07-08  28.032787  21.666667           regular          1        188
1279 2018-07-09  33.157895  11.000000           regular          2        189
1281 2018-07-11  31.653543  20.000000           regular          4        191
1282 2018-07-12  34.335938  19.000000           regular          5        192
1284 2018-07-14  29.007634  19.000000           regular          7        194
1285 2018-07-15  23.458333  11.000000           regular          1        195
1286 2018-07-16  40.860215  19.000000           regular          2        196
1289 2018-07-19  52.371134   8.000000           regular          5        199
1290 2018-07-20  40.318182  13.000000           regular          6        200
1291 2018-07-21  33.966942  27.000000           regular          7        201
1292 2018-07-22  28.532609   5.000000           regular          1        202
1293 2018-07-23  36.392857   9.000000           regular          2        203
1294 2018-07-24  37.009346  29.000000           regular          3        204
1297 2018-07-27  33.916667   7.000000           regular          6        207
1298 2018-07-28  33.615385   8.000000           regular          7        208
1299 2018-07-29  25.663265   2.333333           regular          1        209
1300 2018-07-30  32.803030  20.000000           regular          2        210

      WEEKOFYEAR  MONTHOFYEAR  YEAR                         SEASON  \
0              0            1  2015                 CHRISTMAS PEAK
1              0            1  2015                      CHRISTMAS
2              0            1  2015                      CHRISTMAS
3              1            1  2015                      CHRISTMAS
4              1            1  2015                      CHRISTMAS
5              1            1  2015                      CHRISTMAS
6              1            1  2015                      CHRISTMAS
7              1            1  2015                      CHRISTMAS
8              1            1  2015                      CHRISTMAS
9              1            1  2015                         WINTER
10             2            1  2015                         WINTER
11             2            1  2015                         WINTER
12             2            1  2015                         WINTER
14             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
15             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
16             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
17             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
18             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
19             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
20             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
21             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
22             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
23             3            1  2015                         WINTER
24             4            1  2015                         WINTER
25             4            1  2015                         WINTER
26             4            1  2015                         WINTER
27             4            1  2015                         WINTER
28             4            1  2015                         WINTER
29             4            1  2015                         WINTER
30             4            1  2015                         WINTER
...          ...          ...   ...                            ...
1263          24            6  2018                         SPRING
1264          25            6  2018                         SPRING
1265          25            6  2018                         SPRING
1266          25            6  2018                         SPRING
1267          25            6  2018                         SPRING
1268          25            6  2018                         SPRING
1269          25            6  2018                         SPRING
1270          25            6  2018                         SPRING
1271          26            7  2018                   SUMMER BREAK
1272          26            7  2018                       JULY 4TH
1274          26            7  2018                       JULY 4TH
1276          26            7  2018                       JULY 4TH
1277          26            7  2018                   SUMMER BREAK
1278          27            7  2018                   SUMMER BREAK
1279          27            7  2018                   SUMMER BREAK
1281          27            7  2018                   SUMMER BREAK
1282          27            7  2018                   SUMMER BREAK
1284          27            7  2018                   SUMMER BREAK
1285          28            7  2018                   SUMMER BREAK
1286          28            7  2018                   SUMMER BREAK
1289          28            7  2018                   SUMMER BREAK
1290          28            7  2018                   SUMMER BREAK
1291          28            7  2018                   SUMMER BREAK
1292          29            7  2018                   SUMMER BREAK
1293          29            7  2018                   SUMMER BREAK
1294          29            7  2018                   SUMMER BREAK
1297          29            7  2018                   SUMMER BREAK
1298          29            7  2018                   SUMMER BREAK
1299          30            7  2018                   SUMMER BREAK
1300          30            7  2018                   SUMMER BREAK

           ...         HSFIRET2                            HSFIREN HSSHWNGT  \
0          ...              NaN                                NaN        3
1          ...              NaN                                NaN        3
2          ...              NaN                                NaN        2
3          ...              NaN                                NaN        2
4          ...              NaN                                NaN        2
5          ...              NaN                                NaN        1
6          ...              NaN                                NaN        1
7          ...              NaN                                NaN        1
8          ...              NaN                                NaN        1
9          ...              NaN                                NaN        2
10         ...              NaN                                NaN        1
11         ...              NaN                                NaN        2
12         ...              NaN                                NaN        1
14         ...              NaN                                NaN        1
15         ...              NaN                                NaN        1
16         ...              NaN                                NaN        2
17         ...              NaN                                NaN        2
18         ...              NaN                                NaN        2
19         ...              NaN                                NaN        1
20         ...              NaN                                NaN        1
21         ...              NaN                                NaN        1
22         ...              NaN                                NaN        1
23         ...              NaN                                NaN        2
24         ...              NaN                                NaN        2
25         ...              NaN                                NaN        0
26         ...              NaN                                NaN        2
27         ...              NaN                                NaN        1
28         ...              NaN                                NaN        1
29         ...              NaN                                NaN        1
30         ...              NaN                                NaN        2
...        ...              ...                                ...      ...
1263       ...              NaN  Star Wars: A Galactic Spectacular        1
1264       ...              NaN  Star Wars: A Galactic Spectacular        1
1265       ...              NaN  Star Wars: A Galactic Spectacular        1
1266       ...              NaN  Star Wars: A Galactic Spectacular        1
1267       ...              NaN  Star Wars: A Galactic Spectacular        1
1268       ...              NaN  Star Wars: A Galactic Spectacular        1
1269       ...              NaN  Star Wars: A Galactic Spectacular        1
1270       ...              NaN  Star Wars: A Galactic Spectacular        2
1271       ...              NaN  Star Wars: A Galactic Spectacular        2
1272       ...              NaN  Star Wars: A Galactic Spectacular        2
1274       ...              NaN  Star Wars: A Galactic Spectacular        2
1276       ...              NaN  Star Wars: A Galactic Spectacular        2
1277       ...              NaN  Star Wars: A Galactic Spectacular        2
1278       ...              NaN  Star Wars: A Galactic Spectacular        2
1279       ...              NaN  Star Wars: A Galactic Spectacular        2
1281       ...              NaN  Star Wars: A Galactic Spectacular        2
1282       ...              NaN  Star Wars: A Galactic Spectacular        2
1284       ...              NaN  Star Wars: A Galactic Spectacular        2
1285       ...              NaN  Star Wars: A Galactic Spectacular        2
1286       ...              NaN  Star Wars: A Galactic Spectacular        2
1289       ...              NaN  Star Wars: A Galactic Spectacular        2
1290       ...              NaN  Star Wars: A Galactic Spectacular        2
1291       ...              NaN  Star Wars: A Galactic Spectacular        2
1292       ...              NaN  Star Wars: A Galactic Spectacular        2
1293       ...              NaN  Star Wars: A Galactic Spectacular        2
1294       ...              NaN  Star Wars: A Galactic Spectacular        2
1297       ...              NaN  Star Wars: A Galactic Spectacular        2
1298       ...              NaN  Star Wars: A Galactic Spectacular        2
1299       ...              NaN  Star Wars: A Galactic Spectacular        2
1300       ...              NaN  Star Wars: A Galactic Spectacular        2

      HSSHWNT1 HSSHWNT2     HSSHWNN AKSHWNGT  AKSHWNT1  AKSHWNT2  \
0        18:30    20:00  Fantasmic!        0       NaN       NaN
1        18:30    20:00  Fantasmic!        0       NaN       NaN
2        18:30    20:00  Fantasmic!        0       NaN       NaN
3        19:00    20:30  Fantasmic!        0       NaN       NaN
4        19:00    20:30  Fantasmic!        0       NaN       NaN
5        19:00      NaN  Fantasmic!        0       NaN       NaN
6        19:00      NaN  Fantasmic!        0       NaN       NaN
7        19:00      NaN  Fantasmic!        0       NaN       NaN
8        19:00      NaN  Fantasmic!        0       NaN       NaN
9        19:00    20:30  Fantasmic!        0       NaN       NaN
10       19:00      NaN  Fantasmic!        0       NaN       NaN
11       19:00    20:30  Fantasmic!        0       NaN       NaN
12       19:00      NaN  Fantasmic!        0       NaN       NaN
14       19:00      NaN  Fantasmic!        0       NaN       NaN
15       19:00      NaN  Fantasmic!        0       NaN       NaN
16       19:00    20:30  Fantasmic!        0       NaN       NaN
17       19:00    20:30  Fantasmic!        0       NaN       NaN
18       19:00    20:30  Fantasmic!        0       NaN       NaN
19       19:00      NaN  Fantasmic!        0       NaN       NaN
20       19:00      NaN  Fantasmic!        0       NaN       NaN
21       19:00      NaN  Fantasmic!        0       NaN       NaN
22       19:00      NaN  Fantasmic!        0       NaN       NaN
23       19:00    20:30  Fantasmic!        0       NaN       NaN
24       19:00    20:30  Fantasmic!        0       NaN       NaN
25         NaN      NaN         NaN        0       NaN       NaN
26       19:00    20:30  Fantasmic!        0       NaN       NaN
27       19:00      NaN  Fantasmic!        0       NaN       NaN
28       19:00      NaN  Fantasmic!        0       NaN       NaN
29       19:00      NaN  Fantasmic!        0       NaN       NaN
30       19:00    20:30  Fantasmic!        0       NaN       NaN
...        ...      ...         ...      ...       ...       ...
1263     21:00      NaN  Fantasmic!        2     21:15     22:15
1264     21:00      NaN  Fantasmic!        2     21:15     22:15
1265     21:00      NaN  Fantasmic!        2     21:15     22:15
1266     21:00      NaN  Fantasmic!        2     21:15     22:15
1267     21:00      NaN  Fantasmic!        2     21:15     22:15
1268     21:00      NaN  Fantasmic!        2     21:15     22:15
1269     21:00      NaN  Fantasmic!        2     21:15     22:15
1270     21:00    22:30  Fantasmic!        2     21:15     22:15
1271     21:00    22:30  Fantasmic!        2     21:15     22:15
1272     21:00    22:30  Fantasmic!        2     21:15     22:15
1274     21:00    22:30  Fantasmic!        2     21:15     22:15
1276     21:00    22:30  Fantasmic!        2     21:15     22:15
1277     21:00    22:30  Fantasmic!        2     21:15     22:15
1278     21:00    22:30  Fantasmic!        2     21:15     22:15
1279     21:00    22:30  Fantasmic!        2     21:15     22:15
1281     21:00    22:30  Fantasmic!        2     21:15     22:15
1282     21:00    22:30  Fantasmic!        2     21:15     22:15
1284     21:00    22:30  Fantasmic!        2     21:15     22:15
1285     21:00    22:30  Fantasmic!        2     21:15     22:15
1286     21:00    22:30  Fantasmic!        2     21:15     22:15
1289     21:00    22:30  Fantasmic!        2     21:15     22:15
1290     21:00    22:30  Fantasmic!        2     21:15     22:15
1291     21:00    22:30  Fantasmic!        2     21:15     22:15
1292     21:00    22:30  Fantasmic!        2     21:15     22:15
1293     21:00    22:30  Fantasmic!        2     21:15     22:15
1294     21:00    22:30  Fantasmic!        2     21:15     22:15
1297     21:00    22:30  Fantasmic!        2     21:15     22:15
1298     21:00    22:30  Fantasmic!        2     21:15     22:15
1299     21:00    22:30  Fantasmic!        2     21:15     22:15
1300     21:00    22:30  Fantasmic!        2     21:15     22:15

              AKSHWNN
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
5                 NaN
6                 NaN
7                 NaN
8                 NaN
9                 NaN
10                NaN
11                NaN
12                NaN
14                NaN
15                NaN
16                NaN
17                NaN
18                NaN
19                NaN
20                NaN
21                NaN
22                NaN
23                NaN
24                NaN
25                NaN
26                NaN
27                NaN
28                NaN
29                NaN
30                NaN
...               ...
1263  Rivers of Light
1264  Rivers of Light
1265  Rivers of Light
1266  Rivers of Light
1267  Rivers of Light
1268  Rivers of Light
1269  Rivers of Light
1270  Rivers of Light
1271  Rivers of Light
1272  Rivers of Light
1274  Rivers of Light
1276  Rivers of Light
1277  Rivers of Light
1278  Rivers of Light
1279  Rivers of Light
1281  Rivers of Light
1282  Rivers of Light
1284  Rivers of Light
1285  Rivers of Light
1286  Rivers of Light
1289  Rivers of Light
1290  Rivers of Light
1291  Rivers of Light
1292  Rivers of Light
1293  Rivers of Light
1294  Rivers of Light
1297  Rivers of Light
1298  Rivers of Light
1299  Rivers of Light
1300  Rivers of Light

[1099 rows x 182 columns], 'rock_n_rollercoaster':            date   SPOSTMIN    SACTMIN WDW_TICKET_SEASON  DAYOFWEEK  DAYOFYEAR  \
0    2015-01-01  74.717742  41.200000               NaN          5          0
1    2015-01-02  80.080645  26.000000               NaN          6          1
2    2015-01-03  88.222222  30.000000               NaN          7          2
4    2015-01-05  62.321429  21.000000               NaN          2          4
5    2015-01-06  61.428571  11.000000               NaN          3          5
6    2015-01-07  64.666667  36.000000               NaN          4          6
7    2015-01-08  55.101010  29.666667               NaN          5          7
8    2015-01-09  60.476190  42.000000               NaN          6          8
9    2015-01-10  54.087591  40.333333               NaN          7          9

        date  SACTMIN WDW_TICKET_SEASON  DAYOFWEEK  DAYOFYEAR  WEEKOFYEAR  \
0 2015-01-01     41.2               NaN          5          0           0
1 2015-01-02     26.0               NaN          6          1           0
2 2015-01-03     30.0               NaN          7          2           0
4 2015-01-05     21.0               NaN          2          4           1
5 2015-01-06     11.0               NaN          3          5           1

   MONTHOFYEAR  YEAR          SEASON  HOLIDAYPX   ...     HSFIRET2 HSFIREN  \
0            1  2015  CHRISTMAS PEAK          0   ...          NaN     NaN
1            1  2015       CHRISTMAS          2   ...          NaN     NaN
2            1  2015       CHRISTMAS          3   ...          NaN     NaN
4            1  2015       CHRISTMAS          5   ...          NaN     NaN
5            1  2015       CHRISTMAS          6   ...          NaN     NaN

   HSSHWNGT HSSHWNT1 HSSHWNT2     HSSHWNN  AKSHWNGT  AKSHWNT1 AKSHWNT2  \
0         3    18:30    20:00  Fantasmic!         0       NaN      NaN
1         3    18:30    20:00  Fantasmic!         0       NaN      NaN
2         2    18:30    20:00  Fantasmic!         0       NaN      NaN
4         2    19:00    20:30  Fantasmic!         0       NaN      NaN
5         1    19:00      NaN  Fantasmic!         0       NaN      NaN

   AKSHWNN
0      NaN
1      NaN
2      NaN
4      NaN
5      NaN

[5 rows x 181 columns]
{'expedition_everest':            date   SPOSTMIN    SACTMIN WDW_TICKET_SEASON  DAYOFWEEK  DAYOFYEAR  \
0    2015-01-01  40.268817  10.500000               NaN          5          0
1    2015-01-02  34.198113   5.500000               NaN          6          1
2    2015-01-03  29.793814  24.333333               NaN          7          2
3    2015-01-04  23.850000  25.000000               NaN          1          3
4    2015-01-05  26.956522   3.000000               NaN          2          4
5    2015-01-06  26.666667  10.333333               NaN          3          5
6    2015-01-07  33.283582   9.000000               NaN          4          6
7    2015-01-08  30.846154  35.000000               NaN          5          7
8    2015-01-09  22.631579   7.666667               NaN          6          8
9    2015-01-10  24.340278  27.500000               NaN          7          9
10   2015-01-11  16.127451   9.500000               NaN          1         10
11   2015-01-12  11.936937   0.000000               NaN          2         11
12   2015-01-13   8.137255   3.000000               NaN          3         12
14   2015-01-15  15.891089  11.500000               NaN          5         14
15   2015-01-16  22.809524  22.250000               NaN          6         15
16   2015-01-17  33.308271  20.000000               NaN          7         16
17   2015-01-18  45.843750  16.833333               NaN          1         17
18   2015-01-19  42.163462  16.000000               NaN          2         18
19   2015-01-20  20.280374  33.000000               NaN          3         19
20   2015-01-21  19.303279  14.000000               NaN          4         20
21   2015-01-22  19.714286  13.100000               NaN          5         21
22   2015-01-23  16.495327   8.833333               NaN          6         22
23   2015-01-24  26.111111  20.333333               NaN          7         23
24   2015-01-25  34.126984  33.500000               NaN          1         24
25   2015-01-26  26.168224   4.500000               NaN          2         25
26   2015-01-27  16.941748   8.800000               NaN          3         26
27   2015-01-28  21.666667  17.800000               NaN          4         27
28   2015-01-29  19.634146  15.727273               NaN          5         28
29   2015-01-30  32.142857  19.500000               NaN          6         29
30   2015-01-31  24.712230  27.750000               NaN          7         30
...         ...        ...        ...               ...        ...        ...
1263 2018-06-23  52.946429   7.333333           regular          7        173
1264 2018-06-24  40.930233   5.000000           regular          1        174
1265 2018-06-25  41.000000  15.000000              peak          2        175
1266 2018-06-26  40.312500  70.000000              peak          3        176
1267 2018-06-27  38.333333  12.333333              peak          4        177
1268 2018-06-28  37.948718  14.166667              peak          5        178
1269 2018-06-29  38.956522  10.000000              peak          6        179
1270 2018-06-30  39.400000  24.666667              peak          7        180
1271 2018-07-01  37.520000  12.500000              peak          1        181
1272 2018-07-02  46.822430  26.000000              peak          2        182
1274 2018-07-04  32.198276  34.000000              peak          4        184
1276 2018-07-06  37.425743  31.666667           regular          6        186
1277 2018-07-07  34.956897  14.250000           regular          7        187
1278 2018-07-08  28.032787  21.666667           regular          1        188
1279 2018-07-09  33.157895  11.000000           regular          2        189
1281 2018-07-11  31.653543  20.000000           regular          4        191
1282 2018-07-12  34.335938  19.000000           regular          5        192
1284 2018-07-14  29.007634  19.000000           regular          7        194
1285 2018-07-15  23.458333  11.000000           regular          1        195
1286 2018-07-16  40.860215  19.000000           regular          2        196
1289 2018-07-19  52.371134   8.000000           regular          5        199
1290 2018-07-20  40.318182  13.000000           regular          6        200
1291 2018-07-21  33.966942  27.000000           regular          7        201
1292 2018-07-22  28.532609   5.000000           regular          1        202
1293 2018-07-23  36.392857   9.000000           regular          2        203
1294 2018-07-24  37.009346  29.000000           regular          3        204
1297 2018-07-27  33.916667   7.000000           regular          6        207
1298 2018-07-28  33.615385   8.000000           regular          7        208
1299 2018-07-29  25.663265   2.333333           regular          1        209
1300 2018-07-30  32.803030  20.000000           regular          2        210

      WEEKOFYEAR  MONTHOFYEAR  YEAR                         SEASON  \
0              0            1  2015                 CHRISTMAS PEAK
1              0            1  2015                      CHRISTMAS
2              0            1  2015                      CHRISTMAS
3              1            1  2015                      CHRISTMAS
4              1            1  2015                      CHRISTMAS
5              1            1  2015                      CHRISTMAS
6              1            1  2015                      CHRISTMAS
7              1            1  2015                      CHRISTMAS
8              1            1  2015                      CHRISTMAS
9              1            1  2015                         WINTER
10             2            1  2015                         WINTER
11             2            1  2015                         WINTER
12             2            1  2015                         WINTER
14             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
15             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
16             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
17             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
18             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
19             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
20             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
21             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
22             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
23             3            1  2015                         WINTER
24             4            1  2015                         WINTER
25             4            1  2015                         WINTER
26             4            1  2015                         WINTER
27             4            1  2015                         WINTER
28             4            1  2015                         WINTER
29             4            1  2015                         WINTER
30             4            1  2015                         WINTER
...          ...          ...   ...                            ...
1263          24            6  2018                         SPRING
1264          25            6  2018                         SPRING
1265          25            6  2018                         SPRING
1266          25            6  2018                         SPRING
1267          25            6  2018                         SPRING
1268          25            6  2018                         SPRING
1269          25            6  2018                         SPRING
1270          25            6  2018                         SPRING
1271          26            7  2018                   SUMMER BREAK
1272          26            7  2018                       JULY 4TH
1274          26            7  2018                       JULY 4TH
1276          26            7  2018                       JULY 4TH
1277          26            7  2018                   SUMMER BREAK
1278          27            7  2018                   SUMMER BREAK
1279          27            7  2018                   SUMMER BREAK
1281          27            7  2018                   SUMMER BREAK
1282          27            7  2018                   SUMMER BREAK
1284          27            7  2018                   SUMMER BREAK
1285          28            7  2018                   SUMMER BREAK
1286          28            7  2018                   SUMMER BREAK
1289          28            7  2018                   SUMMER BREAK
1290          28            7  2018                   SUMMER BREAK
1291          28            7  2018                   SUMMER BREAK
1292          29            7  2018                   SUMMER BREAK
1293          29            7  2018                   SUMMER BREAK
1294          29            7  2018                   SUMMER BREAK
1297          29            7  2018                   SUMMER BREAK
1298          29            7  2018                   SUMMER BREAK
1299          30            7  2018                   SUMMER BREAK
1300          30            7  2018                   SUMMER BREAK

           ...         HSFIRET2                            HSFIREN HSSHWNGT  \
0          ...              NaN                                NaN        3
1          ...              NaN                                NaN        3
2          ...              NaN                                NaN        2
3          ...              NaN                                NaN        2
4          ...              NaN                                NaN        2
5          ...              NaN                                NaN        1
6          ...              NaN                                NaN        1
7          ...              NaN                                NaN        1
8          ...              NaN                                NaN        1
9          ...              NaN                                NaN        2
10         ...              NaN                                NaN        1
11         ...              NaN                                NaN        2
12         ...              NaN                                NaN        1
14         ...              NaN                                NaN        1
15         ...              NaN                                NaN        1
16         ...              NaN                                NaN        2
17         ...              NaN                                NaN        2
18         ...              NaN                                NaN        2
19         ...              NaN                                NaN        1
20         ...              NaN                                NaN        1
21         ...              NaN                                NaN        1
22         ...              NaN                                NaN        1
23         ...              NaN                                NaN        2
24         ...              NaN                                NaN        2
25         ...              NaN                                NaN        0
26         ...              NaN                                NaN        2
27         ...              NaN                                NaN        1
28         ...              NaN                                NaN        1
29         ...              NaN                                NaN        1
30         ...              NaN                                NaN        2
...        ...              ...                                ...      ...
1263       ...              NaN  Star Wars: A Galactic Spectacular        1
1264       ...              NaN  Star Wars: A Galactic Spectacular        1
1265       ...              NaN  Star Wars: A Galactic Spectacular        1
1266       ...              NaN  Star Wars: A Galactic Spectacular        1
1267       ...              NaN  Star Wars: A Galactic Spectacular        1
1268       ...              NaN  Star Wars: A Galactic Spectacular        1
1269       ...              NaN  Star Wars: A Galactic Spectacular        1
1270       ...              NaN  Star Wars: A Galactic Spectacular        2
1271       ...              NaN  Star Wars: A Galactic Spectacular        2
1272       ...              NaN  Star Wars: A Galactic Spectacular        2
1274       ...              NaN  Star Wars: A Galactic Spectacular        2
1276       ...              NaN  Star Wars: A Galactic Spectacular        2
1277       ...              NaN  Star Wars: A Galactic Spectacular        2
1278       ...              NaN  Star Wars: A Galactic Spectacular        2
1279       ...              NaN  Star Wars: A Galactic Spectacular        2
1281       ...              NaN  Star Wars: A Galactic Spectacular        2
1282       ...              NaN  Star Wars: A Galactic Spectacular        2
1284       ...              NaN  Star Wars: A Galactic Spectacular        2
1285       ...              NaN  Star Wars: A Galactic Spectacular        2
1286       ...              NaN  Star Wars: A Galactic Spectacular        2
1289       ...              NaN  Star Wars: A Galactic Spectacular        2
1290       ...              NaN  Star Wars: A Galactic Spectacular        2
1291       ...              NaN  Star Wars: A Galactic Spectacular        2
1292       ...              NaN  Star Wars: A Galactic Spectacular        2
1293       ...              NaN  Star Wars: A Galactic Spectacular        2
1294       ...              NaN  Star Wars: A Galactic Spectacular        2
1297       ...              NaN  Star Wars: A Galactic Spectacular        2
1298       ...              NaN  Star Wars: A Galactic Spectacular        2
1299       ...              NaN  Star Wars: A Galactic Spectacular        2
1300       ...              NaN  Star Wars: A Galactic Spectacular        2

      HSSHWNT1 HSSHWNT2     HSSHWNN AKSHWNGT  AKSHWNT1  AKSHWNT2  \
0        18:30    20:00  Fantasmic!        0       NaN       NaN
1        18:30    20:00  Fantasmic!        0       NaN       NaN
2        18:30    20:00  Fantasmic!        0       NaN       NaN
3        19:00    20:30  Fantasmic!        0       NaN       NaN
4        19:00    20:30  Fantasmic!        0       NaN       NaN
5        19:00      NaN  Fantasmic!        0       NaN       NaN
6        19:00      NaN  Fantasmic!        0       NaN       NaN
7        19:00      NaN  Fantasmic!        0       NaN       NaN
8        19:00      NaN  Fantasmic!        0       NaN       NaN
9        19:00    20:30  Fantasmic!        0       NaN       NaN
10       19:00      NaN  Fantasmic!        0       NaN       NaN
11       19:00    20:30  Fantasmic!        0       NaN       NaN
12       19:00      NaN  Fantasmic!        0       NaN       NaN
14       19:00      NaN  Fantasmic!        0       NaN       NaN
15       19:00      NaN  Fantasmic!        0       NaN       NaN
16       19:00    20:30  Fantasmic!        0       NaN       NaN
17       19:00    20:30  Fantasmic!        0       NaN       NaN
18       19:00    20:30  Fantasmic!        0       NaN       NaN
19       19:00      NaN  Fantasmic!        0       NaN       NaN
20       19:00      NaN  Fantasmic!        0       NaN       NaN
21       19:00      NaN  Fantasmic!        0       NaN       NaN
22       19:00      NaN  Fantasmic!        0       NaN       NaN
23       19:00    20:30  Fantasmic!        0       NaN       NaN
24       19:00    20:30  Fantasmic!        0       NaN       NaN
25         NaN      NaN         NaN        0       NaN       NaN
26       19:00    20:30  Fantasmic!        0       NaN       NaN
27       19:00      NaN  Fantasmic!        0       NaN       NaN
28       19:00      NaN  Fantasmic!        0       NaN       NaN
29       19:00      NaN  Fantasmic!        0       NaN       NaN
30       19:00    20:30  Fantasmic!        0       NaN       NaN
...        ...      ...         ...      ...       ...       ...
1263     21:00      NaN  Fantasmic!        2     21:15     22:15
1264     21:00      NaN  Fantasmic!        2     21:15     22:15
1265     21:00      NaN  Fantasmic!        2     21:15     22:15
1266     21:00      NaN  Fantasmic!        2     21:15     22:15
1267     21:00      NaN  Fantasmic!        2     21:15     22:15
1268     21:00      NaN  Fantasmic!        2     21:15     22:15
1269     21:00      NaN  Fantasmic!        2     21:15     22:15
1270     21:00    22:30  Fantasmic!        2     21:15     22:15
1271     21:00    22:30  Fantasmic!        2     21:15     22:15
1272     21:00    22:30  Fantasmic!        2     21:15     22:15
1274     21:00    22:30  Fantasmic!        2     21:15     22:15
1276     21:00    22:30  Fantasmic!        2     21:15     22:15
1277     21:00    22:30  Fantasmic!        2     21:15     22:15
1278     21:00    22:30  Fantasmic!        2     21:15     22:15
1279     21:00    22:30  Fantasmic!        2     21:15     22:15
1281     21:00    22:30  Fantasmic!        2     21:15     22:15
1282     21:00    22:30  Fantasmic!        2     21:15     22:15
1284     21:00    22:30  Fantasmic!        2     21:15     22:15
1285     21:00    22:30  Fantasmic!        2     21:15     22:15
1286     21:00    22:30  Fantasmic!        2     21:15     22:15
1289     21:00    22:30  Fantasmic!        2     21:15     22:15
1290     21:00    22:30  Fantasmic!        2     21:15     22:15
1291     21:00    22:30  Fantasmic!        2     21:15     22:15
1292     21:00    22:30  Fantasmic!        2     21:15     22:15
1293     21:00    22:30  Fantasmic!        2     21:15     22:15
1294     21:00    22:30  Fantasmic!        2     21:15     22:15
1297     21:00    22:30  Fantasmic!        2     21:15     22:15
1298     21:00    22:30  Fantasmic!        2     21:15     22:15
1299     21:00    22:30  Fantasmic!        2     21:15     22:15
1300     21:00    22:30  Fantasmic!        2     21:15     22:15

              AKSHWNN
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
5                 NaN
6                 NaN
7                 NaN
8                 NaN
9                 NaN
10                NaN
11                NaN
12                NaN
14                NaN
15                NaN
16                NaN
17                NaN
18                NaN
19                NaN
20                NaN
21                NaN
22                NaN
23                NaN
24                NaN
25                NaN
26                NaN
27                NaN
28                NaN
29                NaN
30                NaN
...               ...
1263  Rivers of Light
1264  Rivers of Light
1265  Rivers of Light
1266  Rivers of Light

{'expedition_everest':            date   SPOSTMIN    SACTMIN WDW_TICKET_SEASON  DAYOFWEEK  DAYOFYEAR  \
0    2015-01-01  40.268817  10.500000               NaN          5          0
1    2015-01-02  34.198113   5.500000               NaN          6          1
2    2015-01-03  29.793814  24.333333               NaN          7          2
3    2015-01-04  23.850000  25.000000               NaN          1          3
4    2015-01-05  26.956522   3.000000               NaN          2          4
5    2015-01-06  26.666667  10.333333               NaN          3          5
6    2015-01-07  33.283582   9.000000               NaN          4          6
7    2015-01-08  30.846154  35.000000               NaN          5          7
8    2015-01-09  22.631579   7.666667               NaN          6          8
9    2015-01-10  24.340278  27.500000               NaN          7          9
10   2015-01-11  16.127451   9.500000               NaN          1         10
11   2015-01-12  11.936937   0.000000               NaN          2         11
12   2015-01-13   8.137255   3.000000               NaN          3         12
14   2015-01-15  15.891089  11.500000               NaN          5         14
15   2015-01-16  22.809524  22.250000               NaN          6         15
16   2015-01-17  33.308271  20.000000               NaN          7         16
17   2015-01-18  45.843750  16.833333               NaN          1         17
18   2015-01-19  42.163462  16.000000               NaN          2         18
19   2015-01-20  20.280374  33.000000               NaN          3         19
20   2015-01-21  19.303279  14.000000               NaN          4         20
21   2015-01-22  19.714286  13.100000               NaN          5         21
22   2015-01-23  16.495327   8.833333               NaN          6         22
23   2015-01-24  26.111111  20.333333               NaN          7         23
24   2015-01-25  34.126984  33.500000               NaN          1         24
25   2015-01-26  26.168224   4.500000               NaN          2         25
26   2015-01-27  16.941748   8.800000               NaN          3         26
27   2015-01-28  21.666667  17.800000               NaN          4         27
28   2015-01-29  19.634146  15.727273               NaN          5         28
29   2015-01-30  32.142857  19.500000               NaN          6         29
30   2015-01-31  24.712230  27.750000               NaN          7         30
...         ...        ...        ...               ...        ...        ...
1263 2018-06-23  52.946429   7.333333           regular          7        173
1264 2018-06-24  40.930233   5.000000           regular          1        174
1265 2018-06-25  41.000000  15.000000              peak          2        175
1266 2018-06-26  40.312500  70.000000              peak          3        176
1267 2018-06-27  38.333333  12.333333              peak          4        177
1268 2018-06-28  37.948718  14.166667              peak          5        178
1269 2018-06-29  38.956522  10.000000              peak          6        179
1270 2018-06-30  39.400000  24.666667              peak          7        180
1271 2018-07-01  37.520000  12.500000              peak          1        181
1272 2018-07-02  46.822430  26.000000              peak          2        182
1274 2018-07-04  32.198276  34.000000              peak          4        184
1276 2018-07-06  37.425743  31.666667           regular          6        186
1277 2018-07-07  34.956897  14.250000           regular          7        187
1278 2018-07-08  28.032787  21.666667           regular          1        188
1279 2018-07-09  33.157895  11.000000           regular          2        189
1281 2018-07-11  31.653543  20.000000           regular          4        191
1282 2018-07-12  34.335938  19.000000           regular          5        192
1284 2018-07-14  29.007634  19.000000           regular          7        194
1285 2018-07-15  23.458333  11.000000           regular          1        195
1286 2018-07-16  40.860215  19.000000           regular          2        196
1289 2018-07-19  52.371134   8.000000           regular          5        199
1290 2018-07-20  40.318182  13.000000           regular          6        200
1291 2018-07-21  33.966942  27.000000           regular          7        201
1292 2018-07-22  28.532609   5.000000           regular          1        202
1293 2018-07-23  36.392857   9.000000           regular          2        203
1294 2018-07-24  37.009346  29.000000           regular          3        204
1297 2018-07-27  33.916667   7.000000           regular          6        207
1298 2018-07-28  33.615385   8.000000           regular          7        208
1299 2018-07-29  25.663265   2.333333           regular          1        209
1300 2018-07-30  32.803030  20.000000           regular          2        210

      WEEKOFYEAR  MONTHOFYEAR  YEAR                         SEASON  \
0              0            1  2015                 CHRISTMAS PEAK
1              0            1  2015                      CHRISTMAS
2              0            1  2015                      CHRISTMAS
3              1            1  2015                      CHRISTMAS
4              1            1  2015                      CHRISTMAS
5              1            1  2015                      CHRISTMAS
6              1            1  2015                      CHRISTMAS
7              1            1  2015                      CHRISTMAS
8              1            1  2015                      CHRISTMAS
9              1            1  2015                         WINTER
10             2            1  2015                         WINTER
11             2            1  2015                         WINTER
12             2            1  2015                         WINTER
14             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
15             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
16             2            1  2015  MARTIN LUTHER KING JUNIOR DAY
17             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
18             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
19             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
20             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
21             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
22             3            1  2015  MARTIN LUTHER KING JUNIOR DAY
23             3            1  2015                         WINTER
24             4            1  2015                         WINTER
25             4            1  2015                         WINTER
26             4            1  2015                         WINTER
27             4            1  2015                         WINTER
28             4            1  2015                         WINTER
29             4            1  2015                         WINTER
30             4            1  2015                         WINTER
...          ...          ...   ...                            ...
1263          24            6  2018                         SPRING
1264          25            6  2018                         SPRING
1265          25            6  2018                         SPRING
1266          25            6  2018                         SPRING
1267          25            6  2018                         SPRING
1268          25            6  2018                         SPRING
1269          25            6  2018                         SPRING
1270          25            6  2018                         SPRING
1271          26            7  2018                   SUMMER BREAK
1272          26            7  2018                       JULY 4TH
1274          26            7  2018                       JULY 4TH
1276          26            7  2018                       JULY 4TH
1277          26            7  2018                   SUMMER BREAK
1278          27            7  2018                   SUMMER BREAK
1279          27            7  2018                   SUMMER BREAK
1281          27            7  2018                   SUMMER BREAK
1282          27            7  2018                   SUMMER BREAK
1284          27            7  2018                   SUMMER BREAK
1285          28            7  2018                   SUMMER BREAK
1286          28            7  2018                   SUMMER BREAK
1289          28            7  2018                   SUMMER BREAK
1290          28            7  2018                   SUMMER BREAK
1291          28            7  2018                   SUMMER BREAK
1292          29            7  2018                   SUMMER BREAK
1293          29            7  2018                   SUMMER BREAK
1294          29            7  2018                   SUMMER BREAK
1297          29            7  2018                   SUMMER BREAK
1298          29            7  2018                   SUMMER BREAK
1299          30            7  2018                   SUMMER BREAK
1300          30            7  2018                   SUMMER BREAK

           ...         HSFIRET2                            HSFIREN HSSHWNGT  \
0          ...              NaN                                NaN        3
1          ...              NaN                                NaN        3
2          ...              NaN                                NaN        2
3          ...              NaN                                NaN        2
4          ...              NaN                                NaN        2
5          ...              NaN                                NaN        1
6          ...              NaN                                NaN        1
7          ...              NaN                                NaN        1
8          ...              NaN                                NaN        1
9          ...              NaN                                NaN        2
10         ...              NaN                                NaN        1
11         ...              NaN                                NaN        2
12         ...              NaN                                NaN        1
14         ...              NaN                                NaN        1
15         ...              NaN                                NaN        1
16         ...              NaN                                NaN        2
17         ...              NaN                                NaN        2
18         ...              NaN                                NaN        2
19         ...              NaN                                NaN        1
20         ...              NaN                                NaN        1
21         ...              NaN                                NaN        1
22         ...              NaN                                NaN        1
23         ...              NaN                                NaN        2
24         ...              NaN                                NaN        2
25         ...              NaN                                NaN        0
26         ...              NaN                                NaN        2
27         ...              NaN                                NaN        1
28         ...              NaN                                NaN        1
29         ...              NaN                                NaN        1
30         ...              NaN                                NaN        2
...        ...              ...                                ...      ...
1263       ...              NaN  Star Wars: A Galactic Spectacular        1
1264       ...              NaN  Star Wars: A Galactic Spectacular        1
1265       ...              NaN  Star Wars: A Galactic Spectacular        1
1266       ...              NaN  Star Wars: A Galactic Spectacular        1
1267       ...              NaN  Star Wars: A Galactic Spectacular        1
1268       ...              NaN  Star Wars: A Galactic Spectacular        1
1269       ...              NaN  Star Wars: A Galactic Spectacular        1
1270       ...              NaN  Star Wars: A Galactic Spectacular        2
1271       ...              NaN  Star Wars: A Galactic Spectacular        2
1272       ...              NaN  Star Wars: A Galactic Spectacular        2
1274       ...              NaN  Star Wars: A Galactic Spectacular        2
1276       ...              NaN  Star Wars: A Galactic Spectacular        2
1277       ...              NaN  Star Wars: A Galactic Spectacular        2
1278       ...              NaN  Star Wars: A Galactic Spectacular        2
1279       ...              NaN  Star Wars: A Galactic Spectacular        2
1281       ...              NaN  Star Wars: A Galactic Spectacular        2
1282       ...              NaN  Star Wars: A Galactic Spectacular        2
1284       ...              NaN  Star Wars: A Galactic Spectacular        2
1285       ...              NaN  Star Wars: A Galactic Spectacular        2
1286       ...              NaN  Star Wars: A Galactic Spectacular        2
1289       ...              NaN  Star Wars: A Galactic Spectacular        2
1290       ...              NaN  Star Wars: A Galactic Spectacular        2
1291       ...              NaN  Star Wars: A Galactic Spectacular        2
1292       ...              NaN  Star Wars: A Galactic Spectacular        2
1293       ...              NaN  Star Wars: A Galactic Spectacular        2
1294       ...              NaN  Star Wars: A Galactic Spectacular        2
1297       ...              NaN  Star Wars: A Galactic Spectacular        2
1298       ...              NaN  Star Wars: A Galactic Spectacular        2
1299       ...              NaN  Star Wars: A Galactic Spectacular        2
1300       ...              NaN  Star Wars: A Galactic Spectacular        2

      HSSHWNT1 HSSHWNT2     HSSHWNN AKSHWNGT  AKSHWNT1  AKSHWNT2  \
0        18:30    20:00  Fantasmic!        0       NaN       NaN
1        18:30    20:00  Fantasmic!        0       NaN       NaN
2        18:30    20:00  Fantasmic!        0       NaN       NaN
3        19:00    20:30  Fantasmic!        0       NaN       NaN
4        19:00    20:30  Fantasmic!        0       NaN       NaN
5        19:00      NaN  Fantasmic!        0       NaN       NaN
6        19:00      NaN  Fantasmic!        0       NaN       NaN
7        19:00      NaN  Fantasmic!        0       NaN       NaN
8        19:00      NaN  Fantasmic!        0       NaN       NaN
9        19:00    20:30  Fantasmic!        0       NaN       NaN
10       19:00      NaN  Fantasmic!        0       NaN       NaN
11       19:00    20:30  Fantasmic!        0       NaN       NaN
12       19:00      NaN  Fantasmic!        0       NaN       NaN
14       19:00      NaN  Fantasmic!        0       NaN       NaN
15       19:00      NaN  Fantasmic!        0       NaN       NaN
16       19:00    20:30  Fantasmic!        0       NaN       NaN
17       19:00    20:30  Fantasmic!        0       NaN       NaN
18       19:00    20:30  Fantasmic!        0       NaN       NaN
19       19:00      NaN  Fantasmic!        0       NaN       NaN
20       19:00      NaN  Fantasmic!        0       NaN       NaN
21       19:00      NaN  Fantasmic!        0       NaN       NaN
22       19:00      NaN  Fantasmic!        0       NaN       NaN
23       19:00    20:30  Fantasmic!        0       NaN       NaN
24       19:00    20:30  Fantasmic!        0       NaN       NaN
25         NaN      NaN         NaN        0       NaN       NaN
26       19:00    20:30  Fantasmic!        0       NaN       NaN
27       19:00      NaN  Fantasmic!        0       NaN       NaN
28       19:00      NaN  Fantasmic!        0       NaN       NaN
29       19:00      NaN  Fantasmic!        0       NaN       NaN
30       19:00    20:30  Fantasmic!        0       NaN       NaN
...        ...      ...         ...      ...       ...       ...
1263     21:00      NaN  Fantasmic!        2     21:15     22:15
1264     21:00      NaN  Fantasmic!        2     21:15     22:15
1265     21:00      NaN  Fantasmic!        2     21:15     22:15
1266     21:00      NaN  Fantasmic!        2     21:15     22:15
1267     21:00      NaN  Fantasmic!        2     21:15     22:15
1268     21:00      NaN  Fantasmic!        2     21:15     22:15
1269     21:00      NaN  Fantasmic!        2     21:15     22:15
1270     21:00    22:30  Fantasmic!        2     21:15     22:15
1271     21:00    22:30  Fantasmic!        2     21:15     22:15
1272     21:00    22:30  Fantasmic!        2     21:15     22:15
1274     21:00    22:30  Fantasmic!        2     21:15     22:15
1276     21:00    22:30  Fantasmic!        2     21:15     22:15
1277     21:00    22:30  Fantasmic!        2     21:15     22:15
1278     21:00    22:30  Fantasmic!        2     21:15     22:15
1279     21:00    22:30  Fantasmic!        2     21:15     22:15
1281     21:00    22:30  Fantasmic!        2     21:15     22:15
1282     21:00    22:30  Fantasmic!        2     21:15     22:15
1284     21:00    22:30  Fantasmic!        2     21:15     22:15
1285     21:00    22:30  Fantasmic!        2     21:15     22:15
1286     21:00    22:30  Fantasmic!        2     21:15     22:15
1289     21:00    22:30  Fantasmic!        2     21:15     22:15
1290     21:00    22:30  Fantasmic!        2     21:15     22:15
1291     21:00    22:30  Fantasmic!        2     21:15     22:15
1292     21:00    22:30  Fantasmic!        2     21:15     22:15
1293     21:00    22:30  Fantasmic!        2     21:15     22:15
1294     21:00    22:30  Fantasmic!        2     21:15     22:15
1297     21:00    22:30  Fantasmic!        2     21:15     22:15
1298     21:00    22:30  Fantasmic!        2     21:15     22:15
1299     21:00    22:30  Fantasmic!        2     21:15     22:15
1300     21:00    22:30  Fantasmic!        2     21:15     22:15

              AKSHWNN
0                 NaN
1                 NaN
2                 NaN
3                 NaN
4                 NaN
5                 NaN
6                 NaN
7                 NaN
8                 NaN
9                 NaN
10                NaN
11                NaN
12                NaN
14                NaN
15                NaN
16                NaN
17                NaN
18                NaN
19                NaN
20                NaN
21                NaN
22                NaN
23                NaN
24                NaN
25                NaN
26                NaN
27                NaN
28                NaN
29                NaN
30                NaN
...               ...
1263  Rivers of Light
1264  Rivers of Light
1265  Rivers of Light
1266  Rivers of Light
1267  Rivers of Light
1268  Rivers of Light
1269  Rivers of Light
1270  Rivers of Light
1271  Rivers of Light
1272  Rivers of Light
1274  Rivers of Light
1276  Rivers of Light
1277  Rivers of Light
1278  Rivers of Light
1279  Rivers of Light
1281  Rivers of Light
1282  Rivers of Light
1284  Rivers of Light
1285  Rivers of Light
1286  Rivers of Light
1289  Rivers of Light
1290  Rivers of Light
1291  Rivers of Light
1292  Rivers of Light
1293  Rivers of Light
1294  Rivers of Light
1297  Rivers of Light
1298  Rivers of Light
1299  Rivers of Light
1300  Rivers of Light

[1099 rows x 182 columns], 'rock_n_rollercoaster':            date   SPOSTMIN    SACTMIN WDW_TICKET_SEASON  DAYOFWEEK  DAYOFYEAR  \
0    2015-01-01  74.717742  41.200000               NaN          5          0
1    2015-01-02  80.080645  26.000000               NaN          6          1
2    2015-01-03  88.222222  30.000000               NaN          7          2
4    2015-01-05  62.321429  21.000000               NaN          2          4
5    2015-01-06  61.428571  11.000000               NaN          3          5
6    2015-01-07  64.666667  36.000000               NaN          4          6
7    2015-01-08  55.101010  29.666667               NaN          5          7
8    2015-01-09  60.476190  42.000000               NaN          6          8
9    2015-01-10  54.087591  40.333333               NaN          7          9

In [47]:
doof["splash_mountain"].head()

,date,SACTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,HOLIDAYPX,...,HSFIRET2,HSFIREN,HSSHWNGT,HSSHWNT1,HSSHWNT2,HSSHWNN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
0,2015-01-01,11.500000,NaN,5,0,0,1,2015,CHRISTMAS PEAK,0,...,NaN,NaN,3,18:30,20:00,Fantasmic!,0,NaN,NaN,NaN
1,2015-01-02,1.000000,NaN,6,1,0,1,2015,CHRISTMAS,2,...,NaN,NaN,3,18:30,20:00,Fantasmic!,0,NaN,NaN,NaN
2,2015-01-03,37.333333,NaN,7,2,0,1,2015,CHRISTMAS,3,...,NaN,NaN,2,18:30,20:00,Fantasmic!,0,NaN,NaN,NaN
3,2015-01-04,16.000000,NaN,1,3,1,1,2015,CHRISTMAS,4,...,NaN,NaN,2,19:00,20:30,Fantasmic!,0,NaN,NaN,NaN
5,2015-02-01,11.400000,NaN,1,31,5,2,2015,WINTER,0,...,NaN,NaN,1,19:00,NaN,Fantasmic!,0,NaN,NaN,NaN

In [48]:
for doo in doof:
    doof[doo].to_csv(f'Resources/{doo}.csv', index = False)

In [40]:
len(moof["rock_n_rollercoaster"]["SPOSTMIN"].unique)

1289