In [1]:
import pandas as pd
import datetime as dt
import glob
import numpy as np

In [2]:
filelist = glob.glob('*.csv')
filelist.remove('metadata.csv')
filelist

['expedition_everest.csv',
 'rock_n_rollercoaster.csv',
 'soarin.csv',
 'splash_mountain.csv']

In [3]:
filelist[0][:-4]

'expedition_everest'

In [4]:
# For all of the filenames:
foof = {}

for filename in filelist:
    foof[filename[:-4]] = pd.read_csv(filename)

In [5]:
foof["expedition_everest"].tail()

              date             datetime  SPOSTMIN  SACTMIN
228807  10/31/2018  2018-10-31 20:10:00    -999.0      NaN
228808  10/31/2018  2018-10-31 20:17:00    -999.0      NaN
228809  10/31/2018  2018-10-31 20:24:00    -999.0      NaN
228810  10/31/2018  2018-10-31 20:30:00    -999.0      NaN
228811  10/31/2018  2018-10-31 20:38:00    -999.0      NaN

In [6]:
goof = {}

for foo in foof:
    foof[foo]["date"] = pd.to_datetime(foof[foo]["date"], format="%m/%d/%Y")
    foof[foo] = foof[foo][foof[foo]["SPOSTMIN"] != -999.0]
    goof[foo] = foof[foo].groupby("date").mean().reset_index()

In [7]:
type(foof["splash_mountain"]["date"][0])

pandas._libs.tslibs.timestamps.Timestamp

In [8]:
goof["splash_mountain"].tail()

           date   SPOSTMIN    SACTMIN
2197 2018-10-27  32.803738  12.000000
2198 2018-10-28  12.659574  15.500000
2199 2018-10-29  47.047619   3.000000
2200 2018-10-30  20.743802  10.142857
2201 2018-10-31  15.182482  13.000000

In [9]:
metadata = pd.read_csv("metadata.csv")
metadata["DATE"] = pd.to_datetime(metadata["DATE"], format="%m/%d/%Y")
print(type(metadata["DATE"][0]))
metadata.rename(columns={"DATE" : "date"}, inplace=True)

metadata.tail()

<class 'pandas._libs.tslibs.timestamps.Timestamp'>

,date,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,HOLIDAYPX,HOLIDAYM,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
2395,2018-07-26,regular,5,206,29,7,2018,SUMMER BREAK,23,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2396,2018-07-27,regular,6,207,29,7,2018,SUMMER BREAK,24,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2397,2018-07-28,regular,7,208,29,7,2018,SUMMER BREAK,25,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2398,2018-07-29,regular,1,209,30,7,2018,SUMMER BREAK,26,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2399,2018-07-30,regular,2,210,30,7,2018,SUMMER BREAK,27,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light

In [10]:
maxdate = metadata["date"].max()
mindate = "01/01/2015"
print(maxdate)
mask = (metadata['date'] >= mindate) & (metadata['date'] <= maxdate)

2018-07-30 00:00:00

In [11]:
metadata = metadata.loc[mask]
metadata

,date,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,HOLIDAYPX,HOLIDAYM,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
1095,2015-01-01,NaN,5,0,0,1,2015,CHRISTMAS PEAK,0,5,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1096,2015-01-02,NaN,6,1,0,1,2015,CHRISTMAS,2,5,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1097,2015-01-03,NaN,7,2,0,1,2015,CHRISTMAS,3,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1098,2015-01-04,NaN,1,3,1,1,2015,CHRISTMAS,4,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1099,2015-01-05,NaN,2,4,1,1,2015,CHRISTMAS,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1100,2015-01-06,NaN,3,5,1,1,2015,CHRISTMAS,6,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1101,2015-01-07,NaN,4,6,1,1,2015,CHRISTMAS,7,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1102,2015-01-08,NaN,5,7,1,1,2015,CHRISTMAS,8,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1103,2015-01-09,NaN,6,8,1,1,2015,CHRISTMAS,9,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1104,2015-01-10,NaN,7,9,1,1,2015,WINTER,10,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1105,2015-01-11,NaN,1,10,2,1,2015,WINTER,9,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1106,2015-01-12,NaN,2,11,2,1,2015,WINTER,8,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1107,2015-01-13,NaN,3,12,2,1,2015,WINTER,7,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1108,2015-01-14,NaN,4,13,2,1,2015,WINTER,6,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1109,2015-01-15,NaN,5,14,2,1,2015,MARTIN LUTHER KING JUNIOR DAY,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1110,2015-01-16,NaN,6,15,2,1,2015,MARTIN LUTHER KING JUNIOR DAY,4,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1111,2015-01-17,NaN,7,16,2,1,2015,MARTIN LUTHER KING JUNIOR DAY,3,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1112,2015-01-18,NaN,1,17,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,2,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1113,2015-01-19,NaN,2,18,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,0,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1114,2015-01-20,NaN,3,19,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,2,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1115,2015-01-21,NaN,4,20,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,3,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1116,2015-01-22,NaN,5,21,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,4,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1117,2015-01-23,NaN,6,22,3,1,2015,MARTIN LUTHER KING JUNIOR DAY,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1118,2015-01-24,NaN,7,23,3,1,2015,WINTER,6,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1119,2015-01-25,NaN,1,24,4,1,2015,WINTER,7,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1120,2015-01-26,NaN,2,25,4,1,2015,WINTER,7,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1121,2015-01-27,NaN,3,26,4,1,2015,WINTER,6,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1122,2015-01-28,NaN,4,27,4,1,2015,WINTER,5,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1123,2015-01-29,NaN,5,28,4,1,2015,WINTER,4,0,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1124,2015-01-30,NaN,6,29,4,1,2015,WINTER,3,2,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2370,2018-07-01,peak,1,181,26,7,2018,SUMMER BREAK,4,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2371,2018-07-02,peak,2,182,26,7,2018,JULY 4TH,3,4,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2372,2018-07-03,peak,3,183,26,7,2018,JULY 4TH,2,4,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2373,2018-07-04,peak,4,184,26,7,2018,JULY 4TH,0,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2374,2018-07-05,regular,5,185,26,7,2018,JULY 4TH,2,4,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2375,2018-07-06,regular,6,186,26,7,2018,JULY 4TH,3,4,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2376,2018-07-07,regular,7,187,26,7,2018,SUMMER BREAK,4,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2377,2018-07-08,regular,1,188,27,7,2018,SUMMER BREAK,5,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2378,2018-07-09,regular,2,189,27,7,2018,SUMMER BREAK,6,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2379,2018-07-10,regular,3,190,27,7,2018,SUMMER BREAK,7,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2380,2018-07-11,regular,4,191,27,7,2018,SUMMER BREAK,8,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2381,2018-07-12,regular,5,192,27,7,2018,SUMMER BREAK,9,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2382,2018-07-13,regular,6,193,27,7,2018,SUMMER BREAK,10,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2383,2018-07-14,regular,7,194,27,7,2018,SUMMER BREAK,11,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2384,2018-07-15,regular,1,195,28,7,2018,SUMMER BREAK,12,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2385,2018-07-16,regular,2,196,28,7,2018,SUMMER BREAK,13,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2386,2018-07-17,regular,3,197,28,7,2018,SUMMER BREAK,14,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2387,2018-07-18,regular,4,198,28,7,2018,SUMMER BREAK,15,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2388,2018-07-19,regular,5,199,28,7,2018,SUMMER BREAK,16,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2389,2018-07-20,regular,6,200,28,7,2018,SUMMER BREAK,17,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2390,2018-07-21,regular,7,201,28,7,2018,SUMMER BREAK,18,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2391,2018-07-22,regular,1,202,29,7,2018,SUMMER BREAK,19,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2392,2018-07-23,regular,2,203,29,7,2018,SUMMER BREAK,20,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2393,2018-07-24,regular,3,204,29,7,2018,SUMMER BREAK,21,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2394,2018-07-25,regular,4,205,29,7,2018,SUMMER BREAK,22,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2395,2018-07-26,regular,5,206,29,7,2018,SUMMER BREAK,23,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2396,2018-07-27,regular,6,207,29,7,2018,SUMMER BREAK,24,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2397,2018-07-28,regular,7,208,29,7,2018,SUMMER BREAK,25,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2398,2018-07-29,regular,1,209,30,7,2018,SUMMER BREAK,26,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
2399,2018-07-30,regular,2,210,30,7,2018,SUMMER BREAK,27,0,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light

In [12]:
moof = {}
for goo in goof:
    mask = (goof[goo]['date'] >= mindate) & (goof[goo]['date'] <= maxdate)
    goof[goo] = goof[goo].loc[mask]
    print(goo)
    
    print(goof[goo].head())
    moof[goo] = pd.merge(goof[goo], metadata, on = "date")

expedition_everest
           date   SPOSTMIN    SACTMIN
1094 2015-01-01  40.268817  10.500000
1095 2015-01-02  34.198113   5.500000
1096 2015-01-03  29.793814  24.333333
1097 2015-01-04  23.850000  25.000000
1098 2015-01-05  26.956522   3.000000
rock_n_rollercoaster
           date   SPOSTMIN  SACTMIN
1095 2015-01-01  74.717742     41.2
1096 2015-01-02  80.080645     26.0
1097 2015-01-03  88.222222     30.0
1098 2015-01-04   5.000000      NaN
1099 2015-01-05  62.321429     21.0
soarin
           date   SPOSTMIN    SACTMIN
1095 2015-01-01  89.814815  61.000000
1096 2015-01-02  82.389706  24.333333
1097 2015-01-03  73.443396        NaN
1098 2015-01-04  58.069307        NaN
1099 2015-01-05  58.437500        NaN
splash_mountain
          date   SPOSTMIN    SACTMIN
941 2015-01-01  28.156028  11.500000
942 2015-01-02  44.014085   1.000000
943 2015-01-03  43.198529  37.333333
944 2015-01-04  30.992063  16.000000
945 2015-01-31   6.724138        NaN

In [13]:
print(filelist[1])
moof[filelist[1][:-4]].head()

rock_n_rollercoaster.csv

,date,SPOSTMIN,SACTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
0,2015-01-01,74.717742,41.2,NaN,5,0,0,1,2015,CHRISTMAS PEAK,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
1,2015-01-02,80.080645,26.0,NaN,6,1,0,1,2015,CHRISTMAS,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
2,2015-01-03,88.222222,30.0,NaN,7,2,0,1,2015,CHRISTMAS,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
3,2015-01-04,5.000000,NaN,NaN,1,3,1,1,2015,CHRISTMAS,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN
4,2015-01-05,62.321429,21.0,NaN,2,4,1,1,2015,CHRISTMAS,...,1,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN

In [14]:
moof[filelist[1][:-4]].tail()

,date,SPOSTMIN,SACTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
1284,2018-07-26,63.206897,NaN,regular,5,206,29,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
1285,2018-07-27,65.566667,5.6,regular,6,207,29,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
1286,2018-07-28,46.726619,7.0,regular,7,208,29,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
1287,2018-07-29,45.856164,1.0,regular,1,209,30,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light
1288,2018-07-30,46.493056,NaN,regular,2,210,30,7,2018,SUMMER BREAK,...,1,0,NaN,NaN,NaN,NaN,2,21:15,22:15,Rivers of Light

In [15]:
delete = ['AKFIREN', 'AKPRDDAY', 'AKPRDDN', 'AKPRDDT1', 'AKPRDDT2', 'HSPRDDN', 'HSPRDDT1', 'HSFIREWKS', 'HSPRDDAY', 'HSPRDDN', \
          'inSession_SoCal', 'AKEMHETOM', 'AKEMHEYEST', 'DAYOFYEAR', 'WEEKOFYEAR', 'DAYOFWEEK', 'MONTHOFYEAR', 'YEAR', \
          'WDW_TICKET_SEASON', 'HOLIDAYN', 'HOLIDAYJ', 'WDW_TICKET_SEASON','WDWRaceN', 'WDWeventN', 'WDWSEASON', 'MKeventN',\
          'EPeventN', 'HSeventN', 'AKeventN', 'AKeventN', 'MKEMHOPEN', 'MKEMHCLOSE', 'EPEMHOPEN', 'EPEMHCLOSE', 'HSEMHOPEN', \
          'HSEMHCLOSE','AKEMHOPEN','AKEMHCLOSE', 'MKPRDNT1', 'MKPRDNT2', 'MKPRDNN', 'MKFIRET2', 'EPFIRET2', 'HSFIRET1',\
          'HSFIRET2', 'HSFIREN', 'HSSHWNT2', 'AKSHWNT1', 'AKSHWNT2', 'AKSHWNN', 'MKPRDDT2', "WDWTICKETSEASON", 'MKFIRET1'\
          'MKFIREN', 'EPFIRET1', 'EPFIREN', 'HSSHWNT1', 'HSSHWNN']
for moo in moof:
    moof[moo] = moof[moo].drop(delete, axis=1)

In [16]:
print(len(list(moof[moo].columns)))

143

In [17]:

for moo in moof:
    moof[moo] = moof[moo][np.isfinite(moof[moo]['SACTMIN'])]

In [57]:
moof[moo].index[pd.isna(moof[moo]['MKFIRET1'])]

Int64Index([124, 227, 228, 613, 654, 950, 999], dtype='int64')

In [99]:
for moo in moof:
    print(moo)
    print(moof[moo].shape())
    missingIndex = set()
    for i in moof[moo].columns:
        if sum(pd.isna(moof[moo][i])) > 0:
            missingIndex.update(moof[moo].index[pd.isna(moof[moo][i])])
            print(i, sum(pd.isna(moof[moo][i])))
    for i in moof[moo].columns:
        moof[moo] = moof[moo][pd.notna(moof[moo][i])]
    print(len(missingIndex))
    print(moof[moo].shape)

expedition_everest
SPOSTMIN 1
WDWMAXTEMP 5
WDWMINTEMP 6
WDWMEANTEMP 6
MKFIRET1 7
MKFIREN 7
EPFIRET1 1
EPFIREN 1
HSSHWNT1 9
HSSHWNN 9
21
(1099, 143)
(1078, 143)
rock_n_rollercoaster
SPOSTMIN 1
WDWMAXTEMP 4
WDWMINTEMP 5
WDWMEANTEMP 5
MKFIRET1 5
MKFIREN 5
EPFIRET1 2
EPFIREN 2
HSSHWNT1 9
HSSHWNN 9
17
(1061, 143)
(1044, 143)
soarin
WDWMAXTEMP 4
WDWMINTEMP 5
WDWMEANTEMP 5
MKFIRET1 8
MKFIREN 8
EPFIRET1 2
EPFIREN 2
HSSHWNT1 8
HSSHWNN 8
19
(1015, 143)
(996, 143)
splash_mountain
WDWMAXTEMP 4
WDWMINTEMP 4
WDWMEANTEMP 4
MKFIRET1 7
MKFIREN 7
EPFIRET1 1
EPFIREN 1
HSSHWNT1 8
HSSHWNN 8
17
(975, 143)
(958, 143)

In [97]:
len(missingIndex)

17

In [96]:
print(moof[moo].shape)
print(temp.shape)

(975, 143)
(958, 143)

IndexError: index 999 is out of bounds for axis 0 with size 975

In [18]:
moof[moo]

,date,SPOSTMIN,SACTMIN,SEASON,HOLIDAYPX,HOLIDAYM,HOLIDAY,WDWevent,WDWrace,WDWMAXTEMP,...,MKFIRET1,MKFIREN,EPFIREWK,EPFIRET1,EPFIREN,HSFIREWK,HSSHWNGT,HSSHWNT1,HSSHWNN,AKSHWNGT
0,2015-01-01,28.156028,11.500000,CHRISTMAS PEAK,0,5,1,0,0,73.02,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,3,18:30,Fantasmic!,0
1,2015-01-02,44.014085,1.000000,CHRISTMAS,2,5,0,0,0,78.00,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,3,18:30,Fantasmic!,0
2,2015-01-03,43.198529,37.333333,CHRISTMAS,3,0,0,0,0,83.12,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,18:30,Fantasmic!,0
3,2015-01-04,30.992063,16.000000,CHRISTMAS,4,0,0,0,0,83.93,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
5,2015-02-01,16.721311,11.400000,WINTER,0,0,1,0,0,73.34,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
7,2015-02-03,14.233333,2.500000,WINTER,3,0,0,0,0,66.33,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
8,2015-02-04,13.129032,5.000000,WINTER,4,0,0,0,0,73.02,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
9,2015-02-05,5.680000,3.000000,WINTER,5,0,0,0,0,65.22,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
10,2015-02-06,20.843023,14.000000,WINTER,6,0,0,0,0,66.33,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
11,2015-02-07,18.341709,31.000000,WINTER,7,0,0,0,0,71.78,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
12,2015-02-08,19.365079,14.500000,WINTER,7,0,0,0,0,73.58,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
13,2015-02-09,9.594595,3.000000,WINTER,6,0,0,0,0,70.42,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
15,2015-02-11,13.545455,14.500000,WINTER,4,0,0,0,0,66.96,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
16,2015-02-12,21.949686,15.500000,PRESIDENTS WEEK,3,0,0,0,0,71.39,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
17,2015-02-13,16.016043,3.500000,PRESIDENTS WEEK,2,0,0,0,0,59.54,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
20,2015-02-16,34.338624,14.200000,PRESIDENTS WEEK,0,0,1,0,0,74.11,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
22,2015-02-18,18.316327,14.000000,PRESIDENTS WEEK,0,4,1,0,0,60.48,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,0,NaN,NaN,0
24,2015-02-20,9.587912,15.000000,PRESIDENTS WEEK,3,4,0,0,1,55.91,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
25,2015-02-21,20.386598,18.500000,PRESIDENTS WEEK,4,4,0,0,1,70.56,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
26,2015-02-22,28.502825,35.000000,PRESIDENTS WEEK,5,0,0,0,1,80.63,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
27,2015-02-23,25.696970,39.000000,WINTER,6,0,0,0,0,81.34,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
28,2015-02-24,17.329545,18.666667,WINTER,7,0,0,0,0,74.40,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
29,2015-02-25,13.478261,12.666667,WINTER,8,0,0,0,0,73.76,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
30,2015-02-26,10.671141,8.333333,WINTER,9,0,0,0,0,73.67,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
31,2015-02-27,5.638298,1.000000,WINTER,10,0,0,0,0,56.51,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
32,2015-02-28,7.670455,3.000000,WINTER,11,0,0,0,0,66.56,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
33,2015-03-01,25.789474,19.250000,SPRING,12,0,0,0,0,78.54,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
34,2015-03-02,27.542373,21.500000,SPRING,13,0,0,0,0,81.95,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
35,2015-03-03,26.506410,17.000000,SPRING,14,0,0,0,0,82.33,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
36,2015-03-04,16.554878,11.000000,SPRING,14,0,0,0,0,84.15,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1129,2018-06-22,67.083333,48.000000,SPRING,6,0,0,0,0,91.28,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1130,2018-06-23,67.366071,13.500000,SPRING,7,0,0,0,0,91.36,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1131,2018-06-24,59.072581,22.250000,SPRING,8,0,0,0,0,92.40,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1132,2018-06-25,79.854015,15.000000,SPRING,9,0,0,0,0,90.64,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1133,2018-06-26,72.703704,58.000000,SPRING,9,0,0,0,0,90.38,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1134,2018-06-27,73.795620,46.000000,SPRING,8,0,0,0,0,89.41,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1136,2018-06-29,63.876404,18.000000,SPRING,6,0,0,0,0,87.01,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1137,2018-06-30,38.811475,10.500000,SPRING,5,0,0,0,0,85.29,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1138,2018-07-01,52.796610,9.000000,SUMMER BREAK,4,0,0,0,0,88.42,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1140,2018-07-03,69.210526,3.000000,JULY 4TH,2,4,0,0,0,89.62,...,21:15,Disney's Celebrate America! - A,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1141,2018-07-04,70.887097,13.000000,JULY 4TH,0,0,1,0,0,83.87,...,21:15,Disney's Celebrate America! - A,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1142,2018-07-05,70.275591,48.000000,JULY 4TH,2,4,0,0,0,85.88,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1143,2018-07-06,56.296296,31.000000,JULY 4TH,3,4,0,0,0,86.04,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1144,2018-07-07,45.625000,11.750000,SUMMER BREAK,4,0,0,0,0,89.19,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1145,2018-07-08,47.892157,33.500000,SUMMER BREAK,5,0,0,0,0,89.67,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1146,2018-07-09,70.595238,46.000000,SUMMER BREAK,6,0,0,0,0,87.62,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1147,2018-07-10,69.205607,29.500000,SUMMER BREAK,7,0,0,0,0,89.89,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1149,2018-07-12,61.386555,36.000000,SUMMER BREAK,9,0,0,0,0,93.13,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1150,2018-07-13,63.225806,29.000000,SUMMER BREAK,10,0,0,0,0,91.46,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1151,2018-07-14,49.909910,10.000000,SUMMER BREAK,11,0,0,0,0,91.89,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1152,2018-07-15,52.698413,35.600000,SUMMER BREAK,12,0,0,0,0,91.55,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1154,2018-07-17,69.072581,23.000000,SUMMER BREAK,14,0,0,0,0,91.34,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1156,2018-07-19,67.317073,30.666667,SUMMER BREAK,16,0,0,0,0,88.46,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1158,2018-07-21,46.678832,38.000000,SUMMER BREAK,18,0,0,0,0,87.77,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1160,2018-07-23,61.560284,8.000000,SUMMER BREAK,20,0,0,0,0,88.41,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1161,2018-07-24,57.264957,2.000000,SUMMER BREAK,21,0,0,0,0,87.39,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1162,2018-07-25,67.744361,43.666667,SUMMER BREAK,22,0,0,0,0,87.72,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1164,2018-07-27,62.435897,9.000000,SUMMER BREAK,24,0,0,0,0,90.21,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1165,2018-07-28,41.048387,48.333333,SUMMER BREAK,25,0,0,0,0,91.31,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1167,2018-07-30,57.934783,37.666667,SUMMER BREAK,27,0,0,0,0,85.95,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2

In [19]:
doof = {}
for moo in moof:
    print(moo)
    print(moof[moo].isna().sum().sum())
    doof[moo] = moof[moo].drop(["SPOSTMIN"], axis = 1)

expedition_everest
52
rock_n_rollercoaster
47
soarin
50
splash_mountain
44

In [23]:
doof["splash_mountain"]

,date,SACTMIN,SEASON,HOLIDAYPX,HOLIDAYM,HOLIDAY,WDWevent,WDWrace,WDWMAXTEMP,WDWMINTEMP,...,MKFIRET1,MKFIREN,EPFIREWK,EPFIRET1,EPFIREN,HSFIREWK,HSSHWNGT,HSSHWNT1,HSSHWNN,AKSHWNGT
0,2015-01-01,11.500000,CHRISTMAS PEAK,0,5,1,0,0,73.02,59.81,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,3,18:30,Fantasmic!,0
1,2015-01-02,1.000000,CHRISTMAS,2,5,0,0,0,78.00,60.72,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,3,18:30,Fantasmic!,0
2,2015-01-03,37.333333,CHRISTMAS,3,0,0,0,0,83.12,67.31,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,18:30,Fantasmic!,0
3,2015-01-04,16.000000,CHRISTMAS,4,0,0,0,0,83.93,67.97,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
5,2015-02-01,11.400000,WINTER,0,0,1,0,0,73.34,48.70,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
7,2015-02-03,2.500000,WINTER,3,0,0,0,0,66.33,44.24,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
8,2015-02-04,5.000000,WINTER,4,0,0,0,0,73.02,53.63,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
9,2015-02-05,3.000000,WINTER,5,0,0,0,0,65.22,51.80,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
10,2015-02-06,14.000000,WINTER,6,0,0,0,0,66.33,50.30,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
11,2015-02-07,31.000000,WINTER,7,0,0,0,0,71.78,48.31,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
12,2015-02-08,14.500000,WINTER,7,0,0,0,0,73.58,49.22,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
13,2015-02-09,3.000000,WINTER,6,0,0,0,0,70.42,55.13,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
15,2015-02-11,14.500000,WINTER,4,0,0,0,0,66.96,47.46,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
16,2015-02-12,15.500000,PRESIDENTS WEEK,3,0,0,0,0,71.39,45.08,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
17,2015-02-13,3.500000,PRESIDENTS WEEK,2,0,0,0,0,59.54,45.34,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
20,2015-02-16,14.200000,PRESIDENTS WEEK,0,0,1,0,0,74.11,48.85,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
22,2015-02-18,14.000000,PRESIDENTS WEEK,0,4,1,0,0,60.48,47.28,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,0,NaN,NaN,0
24,2015-02-20,15.000000,PRESIDENTS WEEK,3,4,0,0,1,55.91,33.47,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
25,2015-02-21,18.500000,PRESIDENTS WEEK,4,4,0,0,1,70.56,43.12,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
26,2015-02-22,35.000000,PRESIDENTS WEEK,5,0,0,0,1,80.63,54.82,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
27,2015-02-23,39.000000,WINTER,6,0,0,0,0,81.34,59.38,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
28,2015-02-24,18.666667,WINTER,7,0,0,0,0,74.40,62.20,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
29,2015-02-25,12.666667,WINTER,8,0,0,0,0,73.76,59.22,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
30,2015-02-26,8.333333,WINTER,9,0,0,0,0,73.67,56.51,...,20:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
31,2015-02-27,1.000000,WINTER,10,0,0,0,0,56.51,53.46,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
32,2015-02-28,3.000000,WINTER,11,0,0,0,0,66.56,56.28,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
33,2015-03-01,19.250000,SPRING,12,0,0,0,0,78.54,64.53,...,22:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,2,19:00,Fantasmic!,0
34,2015-03-02,21.500000,SPRING,13,0,0,0,0,81.95,63.38,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
35,2015-03-03,17.000000,SPRING,14,0,0,0,0,82.33,63.65,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
36,2015-03-04,11.000000,SPRING,14,0,0,0,0,84.15,64.24,...,21:00,Wishes Nighttime Spectacular,1,21:00,IllumiNations: Reflections of Earth,0,1,19:00,Fantasmic!,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1129,2018-06-22,48.000000,SPRING,6,0,0,0,0,91.28,75.11,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1130,2018-06-23,13.500000,SPRING,7,0,0,0,0,91.36,76.15,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1131,2018-06-24,22.250000,SPRING,8,0,0,0,0,92.40,74.10,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1132,2018-06-25,15.000000,SPRING,9,0,0,0,0,90.64,73.25,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1133,2018-06-26,58.000000,SPRING,9,0,0,0,0,90.38,74.09,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1134,2018-06-27,46.000000,SPRING,8,0,0,0,0,89.41,73.20,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1136,2018-06-29,18.000000,SPRING,6,0,0,0,0,87.01,75.06,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,1,21:00,Fantasmic!,2
1137,2018-06-30,10.500000,SPRING,5,0,0,0,0,85.29,73.59,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1138,2018-07-01,9.000000,SUMMER BREAK,4,0,0,0,0,88.42,72.80,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1140,2018-07-03,3.000000,JULY 4TH,2,4,0,0,0,89.62,75.55,...,21:15,Disney's Celebrate America! - A,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1141,2018-07-04,13.000000,JULY 4TH,0,0,1,0,0,83.87,73.29,...,21:15,Disney's Celebrate America! - A,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1142,2018-07-05,48.000000,JULY 4TH,2,4,0,0,0,85.88,71.43,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1143,2018-07-06,31.000000,JULY 4TH,3,4,0,0,0,86.04,71.96,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1144,2018-07-07,11.750000,SUMMER BREAK,4,0,0,0,0,89.19,71.42,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1145,2018-07-08,33.500000,SUMMER BREAK,5,0,0,0,0,89.67,72.29,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1146,2018-07-09,46.000000,SUMMER BREAK,6,0,0,0,0,87.62,74.40,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1147,2018-07-10,29.500000,SUMMER BREAK,7,0,0,0,0,89.89,74.02,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1149,2018-07-12,36.000000,SUMMER BREAK,9,0,0,0,0,93.13,73.61,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1150,2018-07-13,29.000000,SUMMER BREAK,10,0,0,0,0,91.46,75.46,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1151,2018-07-14,10.000000,SUMMER BREAK,11,0,0,0,0,91.89,74.03,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1152,2018-07-15,35.600000,SUMMER BREAK,12,0,0,0,0,91.55,75.19,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1154,2018-07-17,23.000000,SUMMER BREAK,14,0,0,0,0,91.34,73.82,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1156,2018-07-19,30.666667,SUMMER BREAK,16,0,0,0,0,88.46,76.98,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1158,2018-07-21,38.000000,SUMMER BREAK,18,0,0,0,0,87.77,76.57,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1160,2018-07-23,8.000000,SUMMER BREAK,20,0,0,0,0,88.41,70.26,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1161,2018-07-24,2.000000,SUMMER BREAK,21,0,0,0,0,87.39,74.19,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1162,2018-07-25,43.666667,SUMMER BREAK,22,0,0,0,0,87.72,72.63,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1164,2018-07-27,9.000000,SUMMER BREAK,24,0,0,0,0,90.21,75.70,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1165,2018-07-28,48.333333,SUMMER BREAK,25,0,0,0,0,91.31,74.15,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2
1167,2018-07-30,37.666667,SUMMER BREAK,27,0,0,0,0,85.95,73.62,...,21:15,Happily Ever After,1,21:00,IllumiNations: Reflections of Earth,1,2,21:00,Fantasmic!,2

In [22]:
for doo in doof:
    print(doo)
    print(doof[doo].isna().sum().sum())
    doof[doo].to_csv(f'Resources/{doo}.csv', index = False)

expedition_everest
51
rock_n_rollercoaster
46
soarin
50
splash_mountain
44

In [ ]:
pd.options.display.max_columns = None